---
- name: Create Launch Template
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Create an ec2 launch template
      community.aws.ec2_launch_template:
        name: ansible-ig-launch-template
        image_id: ami-04a0ae173da5807d3
        instance_type: t2.micro
        key_name: 4970
        user_data: "{{ lookup('file', 'UserData.sh') | b64encode }}"
        tags:
          key: Name
          value: ansible-ig-server
        network_interfaces:
          - device_index: 0
            associate_public_ip_address: true
            groups:
              - "{{ ansible_nginx_servers_security_group.group_id }}"
        disable_api_termination: false
