---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Include variables from the config file
      include_vars:
        file: "config.yaml"
        name: config

    - name: Run SQL commands
      postgresql_query:
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "{{ config.passwords.postgres }}"
        login_user: "postgres"
        query: "{{ lookup('file', 'create_db.sql') }}"