---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Run SQL commands
      postgresql_query:
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "{{ config.passwords.rds_password }}"
        login_user: "postgres"
        query: "{{ lookup('file', 'create_db.sql') }}"