---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Create Ansible NLB
      community.aws.elb_network_lb:
        name: ansible-ig-nlb
        subnet_mappings:
          - SubnetId: "{{ public_subnet_1.subnet.id }}"
            AllocationId: eipalloc-01a4163ab2f89b320
          - SubnetId: "{{ public_subnet_2.subnet.id }}"
            AllocationId: eipalloc-0fffe66b365a84d22
        scheme: internet-facing
        state: present
        tags:
          Name: ansible-ig-nlb
        region: us-east-1
        listeners:
          - Protocol: TCP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: ansible-nginx-servers
          - Protocol: TLS
            Port: 443
            Certificates:
              - CertificateArn: arn:aws:acm:us-east-1:832133297976:certificate/69e899cf-8fa4-48fa-8a29-ec1c9e31b80b
            SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
            DefaultActions:
              - Type: forward
                TargetGroupName: ansible-nginx-servers
      register: nlb
