---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Include variables from the config file
      include_vars:
        file: "config.yaml"
        name: config

    - name: Create image_gallery user
      postgresql_user:
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "{{ config.passwords.postgres }}"
        login_user: "postgres"
        name: image_gallery
        password: "{{ config.passwords.image_gallery }}"

    - name: Set postgres to have image_gallery role
      postgresql_query:
        db: postgres
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "{{ config.passwords.postgres }}"
        login_user: "postgres"
        query: "ALTER ROLE postgres WITH image_gallery NOINHERIT;"

    - name: Create image_gallery database
      postgresql_db:
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "{{ config.passwords.postgres }}"
        login_user: "postgres"
        name: image_gallery
        owner: image_gallery

    - name: Set up image_gallery database
      postgresql_query:
        db: image_gallery
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "{{ config.passwords.image_gallery }}"
        login_user: image_gallery
        query:
          - CREATE TABLE users (
              username VARCHAR(100) NOT NULL,
              password VARCHAR(100),
              full_name VARCHAR(200)
            );
          - GRANT SELECT, INSERT, UPDATE, DELETE ON users TO image_gallery;
          - GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO image_gallery;
          - ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO image_gallery;
