---
- hosts: localhost
  gather_facts: False
  tasks:
    - name: Include variables from the config file
      include_vars:
        file: "config.yaml"
        name: config
    
    - name: Create RDS subnet group
      community.aws.rds_subnet_group:
        region: us-east-1
        name: ansible-ig-private-dbgrp
        description: "Ansible Image Gallery private subnet group"
        subnets:
          - "{{ private_subnet_1.subnet.id }}"
          - "{{ private_subnet_2.subnet.id }}"
        state: present

    - name: Create RDS instance
      community.aws.rds_instance:
        region: us-east-1
        db_instance_identifier: ansible-image-gallery
        engine: postgres
        engine_version: 14.7
        instance_type: db.t3.micro
        username: postgres
        password: "{{ config.passwords.postgres }}"
        allocated_storage: 20
        vpc_security_group_ids: "{{ ansible_ig_postgres_security_group.group_id }}"
        db_subnet_group_name: ansible-ig-private-dbgrp
        availability_zone: us-east-1a
        backup_retention_period: 7
        preferred_backup_window: "10:26-10:56"
        preferred_maintenance_window: "mon:08:33-mon:09:03"
        auto_minor_version_upgrade: yes
        publicly_accessible: no
        storage_type: "gp2"
        storage_encrypted: true
        kms_key_id: "arn:aws:kms:us-east-1:832133297976:key/8a21fe5a-6434-4f01-8b3c-22c9fa112053"
        license_model: "postgresql-license"
        state: present

    - name: Wait for RDS instance to become available
      community.aws.rds_instance_info:
        db_instance_identifier: ansible-image-gallery
        region: us-east-1
      register: rds_info
      until: rds_info.instances[0].db_instance_status == 'available'
      retries: 30
      delay: 60
