---
- name: Create Auto Scaling Group
  hosts: localhost
  gather_facts: False
  tasks: 
    - name: Create Auto Scaling Group
      amazon.aws.ec2_asg:
        name: Ansible-ASG
        launch_template:
          version: 1
          launch_template_name: ansible-ig-launch-template
        vpc_zone_identifier:
          - "{{ public_subnet_1.subnet.id }}"
          - "{{ public_subnet_2.subnet.id }}"
        min_size: 2
        max_size: 4
        desired_capacity: 2
        region: us-east-1
