---
- hosts: localhost
  gather_facts: false
  tasks:

    - name: Run SQL commands
      community.postgresql.postgresql_query:
        login_host: "{{ rds_info.instances[0].endpoint.address }}"
        login_password: "spacer55"
        login_user: "postgres"
        query: "{{ lookup('file', 'create_db.sql') }}"