---
- name: Create bastion host
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Include variables from the config file
      include_vars:
        file: "config.yaml"
        name: config

    - name: Create a bastion host instance with a public IP address
      amazon.aws.ec2_instance:
        region: us-east-1
        key_name: 4970
        name: "bastion-host"
        vpc_subnet_id: "{{ public_subnet_1.subnet.id }}"
        instance_type: t2.micro
        security_groups:
          - "{{ ansible_ig_postgres_tag_security_group.group_id }}"
          - "{{ ansible_bastion_host_security_group.group_id }}"
        network:
          assign_public_ip: true
        image_id: ami-04a0ae173da5807d3
        user_data: |
          #!/bin/bash
          yum install -y python3 pip git postgresql15 postgresql-devel gcc python3-devel

          sudo chmod u+w /home/ec2-user

          cat >/home/ec2-user/image_gallery.sql <<EOL
          CREATE USER image_gallery WITH PASSWORD '{{ config.passwords.image_gallery }}';
          GRANT image_gallery TO postgres;
          CREATE DATABASE image_gallery OWNER image_gallery;
          \c image_gallery;
          CREATE TABLE users (
            username VARCHAR(100) NOT NULL,
            password VARCHAR(100),
            full_name VARCHAR(200)
          );
          GRANT SELECT, INSERT, UPDATE, DELETE ON users TO image_gallery;
          GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO image_gallery;
          ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO image_gallery;
          EOL

          PGPASSWORD='{{ config.passwords.postgres }}' psql -h {{ rds_info.instances[0].endpoint.address }} -U postgres -f /home/ec2-user/image_gallery.sql
        state: present
      register: bastion_host
